version: '2.4'

services:
  db:
    image: postgres:15.5
    env_file:
      - ../ToDo/.env
    ports:
      - 5432:5432

  server:
    build: .
    env_file:
      - ../ToDo/.env
    ports:
      - 8000:8000
    volumes:
      - ./:/code/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
